### ISSUE TITLE
Laravel 11 update?

### ISSUE THREAD

**Issue by OccultScientist** [ctsoft-de/laravel-pretty-pagination#6]
Is this planned?

On upgrade via Laravel Shift:

`ctsoft/laravel-pretty-pagination v1.2.0 requires illuminate/routing ^6.0|^7.0|^8.0|^9.0|^10.0 -> satisfiable by illuminate/routing[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev]`

Thanks

**Comment by japafrite** [comment]
Hello,

Nice package and I have the same need
Just a composer.json update like previous versions ?

**Comment by domkrm** [comment]
Done
